backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "../../layouts/MarkdownPostLayout.astro" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "gallery"
  label: "Gallery"
  folder: "src/pages/gallery"
  create: true
  fields:
    - { label: "Title", name: "title", widget: "string" }
    - label: "Images"
      name: "images"
      widget: "list"
      allow_add: true
      field: { label: "Image", name: "image", widget: "image" }
    - label: "Thumbnail"
      name: "thumbnail"
      widget: "image"
      media_library:
        config:
          multiple: false
  